" Turn on line numbers
set number

" Let yourself jump from unsaved files, as explained here:
" https://stackoverflow.com/a/2414883/622049
"
" You typically need this when you're jumping from file to file with tags.
set hidden

" Highlight search results
set hlsearch

" Highlight search results as you type in the string
set incsearch

" Automatically reload files when they change underneath you (for example,
" when you change your working directory in git).
set autoread

" Enable mouse support
set mouse=a

" Disable the arrow keys in normal mode (leave in normal mode)
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Disable the arrow keys in insert mode (send to normal mode)
" https://stackoverflow.com/a/23549041/622049
noremap! <Up> <Esc>
noremap! <Down> <Esc>
noremap! <Left> <Esc>
noremap! <Right> <Esc>

set nocompatible
" Always use four spaces for a tab
" https://stackoverflow.com/a/234578
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab

" Keep copied text on the clipboard when you exit VIM:
" https://stackoverflow.com/a/9381778
autocmd VimLeave * call system("xsel -ib", getreg('+'))
" This variation is your own
autocmd VimLeave * call system("xsel -ip", getreg('*'))

" You also tried this, but it was very hard to setup:
" http://clang.llvm.org/docs/ClangFormat.html#vim-integration
"
" If you installed clang-format with the ubuntu package manager, you need to
" make sure you update the path to clang-format.py based on which clang-format
" package you installed:
" https://askubuntu.com/questions/730609/how-can-i-find-the-directory-to-clang-format
"
" There is a Python interpreter compiled into VIM:
" https://stackoverflow.com/questions/45217522
"
" It looks like it is a Python3 interpreter now:
" https://askubuntu.com/a/821235/612216
" https://reviews.llvm.org/D23319
"
" So, you can’t really use the default clang-format.py installed with ubuntu
" (it’s written for Python2).
autocmd FileType c,cpp,hpp,h ClangFormatAutoEnable

" These lines let you quickly navigate between errors:
" https://github.com/w0rp/ale#faq-navigation
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

set tags=./tags;,tags;

" This lets you open more tabs with vim -p
" https://unix.stackexchange.com/questions/30665/gvim-p-limit-of-opened-tabs
set tabpagemax=100

" The following command was partially inspired by this answer:
" https://stackoverflow.com/a/21931739/622049
"
" You had several problems with early variations on this solution; for
" example, the Ggrep! provided by vim-fugitive opens search results in a new file
" in the /tmp folder rather than in a new buffer, so gf didn't work to follow
" files. Git! had the same problem, so you really couldn't use git-fugitive.
"
" The final solution was based more on this answer:
" https://superuser.com/a/435850/293032
command -nargs=1 Ggr execute 'enew | silent :0read !git g' <q-args> | set syn=cpp | norm 1G

" The following map was inspired by this question:
" https://stackoverflow.com/q/21931116/622049
nnoremap <Leader>f :execute 'Ggr '.expand('<cword>')<cr>

" You select keys to map using :help map-which-keys as suggested here:
" http://vim.wikia.com/wiki/Mapping_keys_in_Vim_-_Tutorial_(Part_2)
:map <F2> :set syn=cpp<CR>

" This mapping copies the current filename to the clipboard; you may want
" to use variations on it as well (manually typed). See:
" https://www.brianstorti.com/vim-registers/
nmap <F1> :let @+=@%<CR>
